services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile.asterisk-basic
    container_name: asterisk-basic
    network_mode: host   # importante para SIP
    volumes:
      - ./etc/asterisk:/etc/asterisk
      - ./var/lib/asterisk:/var/lib/asterisk
    restart: unless-stopped